/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteAdmin } from '../fn/admin-controller/delete-admin';
import { DeleteAdmin$Params } from '../fn/admin-controller/delete-admin';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `deleteAdmin()` */
  static readonly DeleteAdminPath = '/api/admin/add/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAdmin$Response(params: DeleteAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return deleteAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteAdmin(params: DeleteAdmin$Params, context?: HttpContext): Observable<string> {
    return this.deleteAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
