/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addStudent } from '../fn/studiant-controller/add-student';
import { AddStudent$Params } from '../fn/studiant-controller/add-student';
import { deleteStudent } from '../fn/studiant-controller/delete-student';
import { DeleteStudent$Params } from '../fn/studiant-controller/delete-student';
import { exportCsv } from '../fn/studiant-controller/export-csv';
import { ExportCsv$Params } from '../fn/studiant-controller/export-csv';
import { filterByLevel } from '../fn/studiant-controller/filter-by-level';
import { FilterByLevel$Params } from '../fn/studiant-controller/filter-by-level';
import { getAllStudents } from '../fn/studiant-controller/get-all-students';
import { GetAllStudents$Params } from '../fn/studiant-controller/get-all-students';
import { getStudentById } from '../fn/studiant-controller/get-student-by-id';
import { GetStudentById$Params } from '../fn/studiant-controller/get-student-by-id';
import { importCsv } from '../fn/studiant-controller/import-csv';
import { ImportCsv$Params } from '../fn/studiant-controller/import-csv';
import { PageStudiantDto } from '../models/page-studiant-dto';
import { searchStudents } from '../fn/studiant-controller/search-students';
import { SearchStudents$Params } from '../fn/studiant-controller/search-students';
import { StudiantDto } from '../models/studiant-dto';
import { updateStudent } from '../fn/studiant-controller/update-student';
import { UpdateStudent$Params } from '../fn/studiant-controller/update-student';

@Injectable({ providedIn: 'root' })
export class StudiantControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllStudents()` */
  static readonly GetAllStudentsPath = '/api/studiants';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllStudents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudents$Response(params: GetAllStudents$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStudiantDto>> {
    return getAllStudents(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllStudents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStudents(params: GetAllStudents$Params, context?: HttpContext): Observable<PageStudiantDto> {
    return this.getAllStudents$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageStudiantDto>): PageStudiantDto => r.body)
    );
  }

  /** Path part for operation `updateStudent()` */
  static readonly UpdateStudentPath = '/api/studiants';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent$Response(params: UpdateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return updateStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent(params: UpdateStudent$Params, context?: HttpContext): Observable<string> {
    return this.updateStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `addStudent()` */
  static readonly AddStudentPath = '/api/studiants';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addStudent$Response(params: AddStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return addStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addStudent(params: AddStudent$Params, context?: HttpContext): Observable<string> {
    return this.addStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `importCsv()` */
  static readonly ImportCsvPath = '/api/studiants/import';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `importCsv()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  importCsv$Response(params?: ImportCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return importCsv(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `importCsv$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  importCsv(params?: ImportCsv$Params, context?: HttpContext): Observable<string> {
    return this.importCsv$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getStudentById()` */
  static readonly GetStudentByIdPath = '/api/studiants/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStudentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById$Response(params: GetStudentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudiantDto>> {
    return getStudentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStudentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById(params: GetStudentById$Params, context?: HttpContext): Observable<StudiantDto> {
    return this.getStudentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudiantDto>): StudiantDto => r.body)
    );
  }

  /** Path part for operation `deleteStudent()` */
  static readonly DeleteStudentPath = '/api/studiants/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteStudent()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent$Response(params: DeleteStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return deleteStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteStudent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent(params: DeleteStudent$Params, context?: HttpContext): Observable<string> {
    return this.deleteStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `searchStudents()` */
  static readonly SearchStudentsPath = '/api/studiants/search/{username}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchStudents()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchStudents$Response(params: SearchStudents$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStudiantDto>> {
    return searchStudents(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchStudents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchStudents(params: SearchStudents$Params, context?: HttpContext): Observable<PageStudiantDto> {
    return this.searchStudents$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageStudiantDto>): PageStudiantDto => r.body)
    );
  }

  /** Path part for operation `filterByLevel()` */
  static readonly FilterByLevelPath = '/api/studiants/filter/{level}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filterByLevel()` instead.
   *
   * This method doesn't expect any request body.
   */
  filterByLevel$Response(params: FilterByLevel$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStudiantDto>> {
    return filterByLevel(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filterByLevel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filterByLevel(params: FilterByLevel$Params, context?: HttpContext): Observable<PageStudiantDto> {
    return this.filterByLevel$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageStudiantDto>): PageStudiantDto => r.body)
    );
  }

  /** Path part for operation `exportCsv()` */
  static readonly ExportCsvPath = '/api/studiants/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `exportCsv()` instead.
   *
   * This method doesn't expect any request body.
   */
  exportCsv$Response(params?: ExportCsv$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return exportCsv(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `exportCsv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  exportCsv(params?: ExportCsv$Params, context?: HttpContext): Observable<Blob> {
    return this.exportCsv$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
