/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageStudiantDto } from '../../models/page-studiant-dto';

export interface FilterByLevel$Params {
  level: string;
  page: number;
  size: number;
}

export function filterByLevel(http: HttpClient, rootUrl: string, params: FilterByLevel$Params, context?: HttpContext): Observable<StrictHttpResponse<PageStudiantDto>> {
  const rb = new RequestBuilder(rootUrl, filterByLevel.PATH, 'get');
  if (params) {
    rb.query('level', params.level, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageStudiantDto>;
    })
  );
}

filterByLevel.PATH = '/api/studiants/filter/{level}';
