/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { PageableObject } from './models/pageable-object';
export type { PageStudiantDto } from './models/page-studiant-dto';
export type { SortObject } from './models/sort-object';
export type { StudiantDto } from './models/studiant-dto';
