/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { StudiantControllerService } from './services/studiant-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
export { AdminControllerService } from './services/admin-controller.service';
